alias: Browse Web - Perform Google Search
description: ""
trigger:
  - platform: state
    entity_id:
      - input_text.browser_time
condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != 'Empty' }}"
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: pyscript.google_search
    data:
      search_query: "{{ states('input_text.browser_search_query') }}"
      user_input: "{{ states('input_text.browser_user_input') }}"
      title: >-
        {{ states('input_text.browser_title') }} - {{
        states('input_text.browser_time') }}
mode: single
